// Comprehensive list of commercial airlines worldwide (IATA code, ICAO code, name)
export interface AirlineData {
  iata: string;
  icao: string;
  name: string;
}

export const ALL_AIRLINES: AirlineData[] = [
  // === BRAZIL ===
  { iata: "LA", icao: "LAN", name: "LATAM Airlines" },
  { iata: "JJ", icao: "TAM", name: "LATAM Airlines Brasil" },
  { iata: "G3", icao: "GLO", name: "GOL Linhas Aéreas" },
  { iata: "AD", icao: "AZU", name: "Azul" },
  { iata: "2Z", icao: "VES", name: "Voepass (Passaredo)" },
  { iata: "O6", icao: "ONE", name: "Avianca Brasil" },
  { iata: "M3", icao: "TUS", name: "LATAM Cargo Brasil" },
  // === LATIN AMERICA & CARIBBEAN ===
  { iata: "AV", icao: "AVA", name: "Avianca" },
  { iata: "CM", icao: "CMP", name: "Copa Airlines" },
  { iata: "AR", icao: "ARG", name: "Aerolíneas Argentinas" },
  { iata: "AM", icao: "AMX", name: "Aeroméxico" },
  { iata: "DM", icao: "ARJ", name: "Arajet" },
  { iata: "4O", icao: "AIJ", name: "Interjet" },
  { iata: "Y4", icao: "VOI", name: "Volaris" },
  { iata: "VB", icao: "VIV", name: "VivaAerobus" },
  { iata: "H2", icao: "SKU", name: "SKY Airline" },
  { iata: "UC", icao: "LCO", name: "LATAM Cargo Chile" },
  { iata: "WJ", icao: "LAB", name: "Boliviana de Aviación (BoA)" },
  { iata: "PZ", icao: "LAP", name: "LATAM Airlines Paraguay" },
  { iata: "XL", icao: "LNE", name: "LATAM Airlines Ecuador" },
  { iata: "LP", icao: "LPE", name: "LATAM Airlines Perú" },
  { iata: "LR", icao: "LRC", name: "LACSA (Avianca Costa Rica)" },
  { iata: "TA", icao: "TAI", name: "TACA (Avianca El Salvador)" },
  { iata: "4C", icao: "ARE", name: "LATAM Airlines Colombia" },
  { iata: "BW", icao: "BWA", name: "Caribbean Airlines" },
  { iata: "UP", icao: "BHS", name: "Bahamasair" },
  { iata: "BM", icao: "BMR", name: "BMI Regional" },
  { iata: "GY", icao: "GEL", name: "Colorful Guizhou Airlines" },
  { iata: "NK", icao: "NKS", name: "Spirit Airlines" },
  { iata: "JA", icao: "BON", name: "JetSMART" },
  { iata: "WE", icao: "THD", name: "Thai Smile" },
  { iata: "FO", icao: "FIA", name: "Flybondi" },
  { iata: "5J", icao: "CEB", name: "Cebu Pacific" },
  { iata: "XP", icao: "CXP", name: "Xtra Airways" },
  { iata: "VR", icao: "TCV", name: "TACV Cabo Verde Airlines" },
  { iata: "P5", icao: "RPB", name: "Wingo" },
  { iata: "2K", icao: "GLG", name: "Avianca Ecuador" },
  { iata: "4M", icao: "DSM", name: "LATAM Airlines Argentina" },
  { iata: "GF", icao: "GFA", name: "Gulf Air" },
  // === USA & CANADA ===
  { iata: "AA", icao: "AAL", name: "American Airlines" },
  { iata: "UA", icao: "UAL", name: "United Airlines" },
  { iata: "DL", icao: "DAL", name: "Delta Air Lines" },
  { iata: "WN", icao: "SWA", name: "Southwest Airlines" },
  { iata: "B6", icao: "JBU", name: "JetBlue Airways" },
  { iata: "AS", icao: "ASA", name: "Alaska Airlines" },
  { iata: "F9", icao: "FFT", name: "Frontier Airlines" },
  { iata: "G4", icao: "AAY", name: "Allegiant Air" },
  { iata: "SY", icao: "SCX", name: "Sun Country Airlines" },
  { iata: "HA", icao: "HAL", name: "Hawaiian Airlines" },
  { iata: "MX", icao: "MXA", name: "Breeze Airways" },
  { iata: "AC", icao: "ACA", name: "Air Canada" },
  { iata: "WS", icao: "WJA", name: "WestJet" },
  { iata: "PD", icao: "POE", name: "Porter Airlines" },
  { iata: "TS", icao: "TSC", name: "Air Transat" },
  { iata: "WO", icao: "WOS", name: "Swoop" },
  { iata: "MO", icao: "CAW", name: "Calm Air" },
  { iata: "4N", icao: "ANT", name: "Air North" },
  // === EUROPE ===
  { iata: "BA", icao: "BAW", name: "British Airways" },
  { iata: "LH", icao: "DLH", name: "Lufthansa" },
  { iata: "AF", icao: "AFR", name: "Air France" },
  { iata: "KL", icao: "KLM", name: "KLM Royal Dutch Airlines" },
  { iata: "IB", icao: "IBE", name: "Iberia" },
  { iata: "AZ", icao: "ITY", name: "ITA Airways" },
  { iata: "TP", icao: "TAP", name: "TAP Air Portugal" },
  { iata: "LX", icao: "SWR", name: "Swiss International Air Lines" },
  { iata: "OS", icao: "AUA", name: "Austrian Airlines" },
  { iata: "SN", icao: "BEL", name: "Brussels Airlines" },
  { iata: "SK", icao: "SAS", name: "SAS Scandinavian Airlines" },
  { iata: "AY", icao: "FIN", name: "Finnair" },
  { iata: "LO", icao: "LOT", name: "LOT Polish Airlines" },
  { iata: "OK", icao: "CSA", name: "Czech Airlines" },
  { iata: "RO", icao: "ROT", name: "TAROM" },
  { iata: "BT", icao: "BTI", name: "airBaltic" },
  { iata: "A3", icao: "AEE", name: "Aegean Airlines" },
  { iata: "TK", icao: "THY", name: "Turkish Airlines" },
  { iata: "SU", icao: "AFL", name: "Aeroflot" },
  { iata: "PS", icao: "AUI", name: "Ukraine International Airlines" },
  { iata: "BJ", icao: "LBT", name: "Nouvelair" },
  { iata: "JU", icao: "JAT", name: "Air Serbia" },
  { iata: "OU", icao: "CTN", name: "Croatia Airlines" },
  { iata: "JP", icao: "ADR", name: "Adria Airways" },
  { iata: "OA", icao: "OAL", name: "Olympic Air" },
  { iata: "EI", icao: "EIN", name: "Aer Lingus" },
  { iata: "FI", icao: "ICE", name: "Icelandair" },
  { iata: "DY", icao: "NAX", name: "Norwegian Air Shuttle" },
  { iata: "DI", icao: "NRS", name: "Norwegian Air International" },
  { iata: "D8", icao: "IBK", name: "Norwegian Air Sweden" },
  { iata: "W6", icao: "WZZ", name: "Wizz Air" },
  { iata: "FR", icao: "RYR", name: "Ryanair" },
  { iata: "U2", icao: "EZY", name: "easyJet" },
  { iata: "LS", icao: "EXS", name: "Jet2.com" },
  { iata: "V7", icao: "VOE", name: "Volotea" },
  { iata: "VY", icao: "VLG", name: "Vueling" },
  { iata: "TO", icao: "TVF", name: "Transavia France" },
  { iata: "HV", icao: "TRA", name: "Transavia" },
  { iata: "PC", icao: "PGT", name: "Pegasus Airlines" },
  { iata: "XQ", icao: "SXS", name: "SunExpress" },
  { iata: "XC", icao: "CAI", name: "Corendon Airlines" },
  { iata: "TU", icao: "TAR", name: "Tunisair" },
  { iata: "DE", icao: "CFG", name: "Condor" },
  { iata: "X3", icao: "TUI", name: "TUI fly Deutschland" },
  { iata: "EW", icao: "EWG", name: "Eurowings" },
  { iata: "4U", icao: "GWI", name: "Germanwings" },
  { iata: "EN", icao: "DLA", name: "Air Dolomiti" },
  { iata: "2L", icao: "OAW", name: "Helvetic Airways" },
  { iata: "WK", icao: "EDW", name: "Edelweiss Air" },
  { iata: "A5", icao: "HOP", name: "HOP!" },
  { iata: "SS", icao: "CRL", name: "Corsair International" },
  { iata: "BF", icao: "FBU", name: "French Bee" },
  { iata: "TX", icao: "FWI", name: "Air Caraïbes" },
  { iata: "UX", icao: "AEA", name: "Air Europa" },
  { iata: "I2", icao: "IBS", name: "Iberia Express" },
  { iata: "YW", icao: "ANE", name: "Air Nostrum" },
  { iata: "0B", icao: "BMS", name: "Blue Air" },
  { iata: "FB", icao: "LZB", name: "Bulgaria Air" },
  { iata: "W2", icao: "FLX", name: "FlexFlight" },
  { iata: "RC", icao: "FLI", name: "Atlantic Airways" },
  { iata: "GL", icao: "GRL", name: "Air Greenland" },
  { iata: "WF", icao: "WIF", name: "Widerøe" },
  { iata: "QI", icao: "CIM", name: "Cimber Sterling" },
  { iata: "SI", icao: "BCI", name: "Blue Islands" },
  { iata: "BE", icao: "BEE", name: "Flybe" },
  { iata: "LG", icao: "LGL", name: "Luxair" },
  { iata: "S4", icao: "RZO", name: "SATA Azores Airlines" },
  { iata: "NI", icao: "PGA", name: "Portugália Airlines" },
  // === MIDDLE EAST ===
  { iata: "EK", icao: "UAE", name: "Emirates" },
  { iata: "QR", icao: "QTR", name: "Qatar Airways" },
  { iata: "EY", icao: "ETD", name: "Etihad Airways" },
  { iata: "SV", icao: "SVA", name: "Saudi Arabian Airlines (Saudia)" },
  { iata: "GF", icao: "GFA", name: "Gulf Air" },
  { iata: "WY", icao: "OMA", name: "Oman Air" },
  { iata: "KU", icao: "KAC", name: "Kuwait Airways" },
  { iata: "RJ", icao: "RJA", name: "Royal Jordanian" },
  { iata: "ME", icao: "MEA", name: "Middle East Airlines (MEA)" },
  { iata: "G9", icao: "ABY", name: "Air Arabia" },
  { iata: "FZ", icao: "FDB", name: "flydubai" },
  { iata: "XY", icao: "KNE", name: "flynas" },
  { iata: "J9", icao: "JZR", name: "Jazeera Airways" },
  { iata: "R5", icao: "JAV", name: "Jordan Aviation" },
  { iata: "E5", icao: "RSO", name: "Air Arabia Egypt" },
  { iata: "3L", icao: "SAQ", name: "Air Arabia Abu Dhabi" },
  { iata: "IF", icao: "ISW", name: "FlyBaghdad" },
  // === AFRICA ===
  { iata: "ET", icao: "ETH", name: "Ethiopian Airlines" },
  { iata: "SA", icao: "SAA", name: "South African Airways" },
  { iata: "KQ", icao: "KQA", name: "Kenya Airways" },
  { iata: "MS", icao: "MSR", name: "EgyptAir" },
  { iata: "AT", icao: "RAM", name: "Royal Air Maroc" },
  { iata: "WB", icao: "RWD", name: "RwandAir" },
  { iata: "TC", icao: "ATC", name: "Air Tanzania" },
  { iata: "TM", icao: "LAM", name: "LAM Mozambique Airlines" },
  { iata: "UM", icao: "AZW", name: "Air Zimbabwe" },
  { iata: "HF", icao: "HAG", name: "Air Côte d'Ivoire" },
  { iata: "W3", icao: "ARA", name: "Arik Air" },
  { iata: "P4", icao: "APK", name: "Air Peace" },
  { iata: "MN", icao: "CAW", name: "Comair (South Africa)" },
  { iata: "FA", icao: "SFR", name: "FlySafair" },
  { iata: "MK", icao: "MAU", name: "Air Mauritius" },
  { iata: "HM", icao: "SEY", name: "Air Seychelles" },
  { iata: "MD", icao: "MDG", name: "Air Madagascar" },
  { iata: "DT", icao: "DTA", name: "TAAG Angola Airlines" },
  { iata: "QC", icao: "CRN", name: "Camair-Co" },
  { iata: "A7", icao: "MPD", name: "Air Plus Comet" },
  { iata: "ZF", icao: "AZG", name: "AZMAN Air" },
  // === ASIA - EAST ===
  { iata: "CX", icao: "CPA", name: "Cathay Pacific" },
  { iata: "KA", icao: "HDA", name: "Cathay Dragon" },
  { iata: "HX", icao: "CRK", name: "Hong Kong Airlines" },
  { iata: "UO", icao: "HKE", name: "HK Express" },
  { iata: "CA", icao: "CCA", name: "Air China" },
  { iata: "MU", icao: "CES", name: "China Eastern Airlines" },
  { iata: "CZ", icao: "CSN", name: "China Southern Airlines" },
  { iata: "HU", icao: "CHH", name: "Hainan Airlines" },
  { iata: "3U", icao: "CSC", name: "Sichuan Airlines" },
  { iata: "ZH", icao: "CSZ", name: "Shenzhen Airlines" },
  { iata: "MF", icao: "CXA", name: "Xiamen Airlines" },
  { iata: "SC", icao: "CDG", name: "Shandong Airlines" },
  { iata: "FM", icao: "CSH", name: "Shanghai Airlines" },
  { iata: "TV", icao: "TBZ", name: "Tibet Airlines" },
  { iata: "GJ", icao: "CDC", name: "Zhejiang Loong Airlines" },
  { iata: "9C", icao: "CQH", name: "Spring Airlines" },
  { iata: "G5", icao: "HBH", name: "China Express Airlines" },
  { iata: "EU", icao: "UEA", name: "Chengdu Airlines" },
  { iata: "KN", icao: "CUA", name: "China United Airlines" },
  { iata: "PN", icao: "CHB", name: "West Air (China)" },
  { iata: "DZ", icao: "EPA", name: "Donghai Airlines" },
  { iata: "QW", icao: "CQN", name: "Qingdao Airlines" },
  { iata: "JD", icao: "CBJ", name: "Beijing Capital Airlines" },
  { iata: "AQ", icao: "JYH", name: "9 Air" },
  { iata: "JL", icao: "JAL", name: "Japan Airlines (JAL)" },
  { iata: "NH", icao: "ANA", name: "All Nippon Airways (ANA)" },
  { iata: "BC", icao: "SKY", name: "Skymark Airlines" },
  { iata: "MM", icao: "APJ", name: "Peach Aviation" },
  { iata: "GK", icao: "JJP", name: "Jetstar Japan" },
  { iata: "7G", icao: "SFJ", name: "StarFlyer" },
  { iata: "HD", icao: "ADO", name: "AIRDO" },
  { iata: "3K", icao: "JSA", name: "Jetstar Asia" },
  { iata: "KE", icao: "KAL", name: "Korean Air" },
  { iata: "OZ", icao: "AAR", name: "Asiana Airlines" },
  { iata: "BX", icao: "ABL", name: "Air Busan" },
  { iata: "LJ", icao: "JNA", name: "Jin Air" },
  { iata: "TW", icao: "TWB", name: "T'way Air" },
  { iata: "ZE", icao: "ESR", name: "Eastar Jet" },
  { iata: "RS", icao: "ASV", name: "Air Seoul" },
  { iata: "7C", icao: "JJA", name: "Jeju Air" },
  { iata: "RF", icao: "FPA", name: "Aero K" },
  { iata: "CI", icao: "CAL", name: "China Airlines" },
  { iata: "BR", icao: "EVA", name: "EVA Air" },
  { iata: "IT", icao: "TTW", name: "Tigerair Taiwan" },
  { iata: "B7", icao: "UIA", name: "Uni Air" },
  { iata: "AE", icao: "MDA", name: "Mandarin Airlines" },
  { iata: "FE", icao: "FEA", name: "Far Eastern Air Transport" },
  { iata: "BL", icao: "PIC", name: "Pacific Airlines (Vietnam)" },
  { iata: "VN", icao: "HVN", name: "Vietnam Airlines" },
  { iata: "VJ", icao: "VJC", name: "VietJet Air" },
  { iata: "QH", icao: "BAV", name: "Bamboo Airways" },
  // === ASIA - SOUTH EAST ===
  { iata: "SQ", icao: "SIA", name: "Singapore Airlines" },
  { iata: "TR", icao: "TGW", name: "Scoot" },
  { iata: "MI", icao: "SLK", name: "SilkAir" },
  { iata: "MH", icao: "MAS", name: "Malaysia Airlines" },
  { iata: "AK", icao: "AXM", name: "AirAsia" },
  { iata: "D7", icao: "XAX", name: "AirAsia X" },
  { iata: "FD", icao: "AIQ", name: "Thai AirAsia" },
  { iata: "QZ", icao: "AWQ", name: "Indonesia AirAsia" },
  { iata: "Z2", icao: "EZD", name: "Philippines AirAsia" },
  { iata: "OD", icao: "MXD", name: "Batik Air Malaysia" },
  { iata: "TG", icao: "THA", name: "Thai Airways" },
  { iata: "GA", icao: "GIA", name: "Garuda Indonesia" },
  { iata: "JT", icao: "LNI", name: "Lion Air" },
  { iata: "ID", icao: "BTK", name: "Batik Air (Indonesia)" },
  { iata: "QG", icao: "CTV", name: "Citilink" },
  { iata: "IN", icao: "NAM", name: "NAM Air" },
  { iata: "IW", icao: "WON", name: "Wings Air" },
  { iata: "PR", icao: "PAL", name: "Philippine Airlines" },
  { iata: "DG", icao: "CEB", name: "Cebgo" },
  { iata: "8M", icao: "MMA", name: "Myanmar Airways International" },
  { iata: "UB", icao: "UBA", name: "Myanmar National Airlines" },
  { iata: "K6", icao: "KHM", name: "Cambodia Angkor Air" },
  { iata: "QV", icao: "LAO", name: "Lao Airlines" },
  { iata: "BI", icao: "RBA", name: "Royal Brunei Airlines" },
  // === ASIA - SOUTH ===
  { iata: "AI", icao: "AIC", name: "Air India" },
  { iata: "IX", icao: "AXB", name: "Air India Express" },
  { iata: "6E", icao: "IGO", name: "IndiGo" },
  { iata: "SG", icao: "SEJ", name: "SpiceJet" },
  { iata: "UK", icao: "VTI", name: "Vistara" },
  { iata: "G8", icao: "GOW", name: "Go First (GoAir)" },
  { iata: "I5", icao: "IAD", name: "AirAsia India" },
  { iata: "QP", icao: "BLV", name: "Akasa Air" },
  { iata: "PK", icao: "PIA", name: "Pakistan International Airlines (PIA)" },
  { iata: "UL", icao: "ALK", name: "SriLankan Airlines" },
  { iata: "BG", icao: "BBC", name: "Biman Bangladesh Airlines" },
  { iata: "BS", icao: "BIS", name: "US-Bangla Airlines" },
  { iata: "RA", icao: "RNA", name: "Nepal Airlines" },
  { iata: "YT", icao: "YTI", name: "Yeti Airlines" },
  { iata: "KB", icao: "DRK", name: "Druk Air (Royal Bhutan)" },
  { iata: "Q2", icao: "DQA", name: "Maldivian" },
  // === ASIA - CENTRAL ===
  { iata: "KC", icao: "KZR", name: "Air Astana" },
  { iata: "HY", icao: "UZB", name: "Uzbekistan Airways" },
  { iata: "T5", icao: "TUA", name: "Turkmenistan Airlines" },
  { iata: "7J", icao: "TJK", name: "Tajik Air" },
  { iata: "QH", icao: "KGA", name: "Kyrgyzstan Air" },
  // === OCEANIA ===
  { iata: "QF", icao: "QFA", name: "Qantas" },
  { iata: "JQ", icao: "JST", name: "Jetstar Airways" },
  { iata: "VA", icao: "VOZ", name: "Virgin Australia" },
  { iata: "ZL", icao: "RXA", name: "Rex Airlines" },
  { iata: "TT", icao: "TGG", name: "Tigerair Australia" },
  { iata: "NZ", icao: "ANZ", name: "Air New Zealand" },
  { iata: "FJ", icao: "FJI", name: "Fiji Airways" },
  { iata: "NF", icao: "AVN", name: "Air Vanuatu" },
  { iata: "SB", icao: "ACI", name: "Aircalin" },
  { iata: "IE", icao: "SOL", name: "Solomon Airlines" },
  { iata: "PX", icao: "ANG", name: "Air Niugini" },
  { iata: "TN", icao: "THT", name: "Air Tahiti Nui" },
  { iata: "DJ", icao: "VOZ", name: "Virgin Australia Regional" },
  // === LOW COST (additional not listed above) ===
  { iata: "WW", icao: "WOW", name: "WOW air" },
  { iata: "XR", icao: "CXI", name: "Corendon Airlines Europe" },
  { iata: "ZI", icao: "AAF", name: "Aigle Azur" },
  { iata: "QS", icao: "TVS", name: "SmartWings" },
  { iata: "8Q", icao: "OHY", name: "Onur Air" },
  { iata: "XK", icao: "CCM", name: "Air Corsica" },
  { iata: "VF", icao: "VFC", name: "Valuejet" },
  { iata: "DP", icao: "FCA", name: "Pobeda" },
  { iata: "5O", icao: "FIV", name: "ASL Airlines France" },
  { iata: "6B", icao: "BLX", name: "TUIfly Nordic" },
  { iata: "TB", icao: "JAF", name: "TUI fly Belgium" },
  { iata: "BY", icao: "TOM", name: "TUI Airways" },
  { iata: "OR", icao: "TFL", name: "TUI fly Netherlands" },
  { iata: "HG", icao: "NLY", name: "NIKI (Lauda)" },
  { iata: "OE", icao: "LDA", name: "Lauda Europe" },
  { iata: "W4", icao: "WZU", name: "Wizz Air Malta" },
  { iata: "W9", icao: "WZA", name: "Wizz Air Abu Dhabi" },
  { iata: "RK", icao: "RKA", name: "Ryanair UK" },
  { iata: "EC", icao: "EZS", name: "easyJet Switzerland" },
  { iata: "DS", icao: "EZS", name: "easyJet UK" },
  // === CARGO (major) ===
  { iata: "FX", icao: "FDX", name: "FedEx Express" },
  { iata: "5X", icao: "UPS", name: "UPS Airlines" },
  { iata: "CV", icao: "CLU", name: "Cargolux" },
  { iata: "5Y", icao: "GTI", name: "Atlas Air" },
  // === CHARTER / SPECIALTY ===
  { iata: "5K", icao: "HFY", name: "Hi Fly" },
  { iata: "EB", icao: "PLM", name: "Wamos Air" },
  { iata: "SM", icao: "MPH", name: "Air Cairo" },
  { iata: "E4", icao: "RSO", name: "Enter Air" },
  // === ADDITIONAL GLOBAL ===
  { iata: "IR", icao: "IRA", name: "Iran Air" },
  { iata: "W5", icao: "IRM", name: "Mahan Air" },
  { iata: "EP", icao: "IRC", name: "Iran Aseman Airlines" },
  { iata: "IV", icao: "JET", name: "Jet Airways (India)" },
  { iata: "RB", icao: "SYR", name: "Syrian Air" },
  { iata: "LY", icao: "ELY", name: "El Al Israel Airlines" },
  { iata: "6H", icao: "ISR", name: "Israir Airlines" },
  { iata: "IZ", icao: "AIZ", name: "Arkia Israeli Airlines" },
  { iata: "PG", icao: "BKP", name: "Bangkok Airways" },
  { iata: "OG", icao: "PTN", name: "PLAY (Iceland)" },
  { iata: "ST", icao: "GMI", name: "Germania" },
  { iata: "4T", icao: "BHP", name: "Beond" },
  { iata: "UJ", icao: "ALM", name: "AlMasria Universal Airlines" },
  { iata: "NE", icao: "NES", name: "Nesma Airlines" },
  { iata: "J4", icao: "BDJ", name: "Badr Airlines" },
  { iata: "5P", icao: "FIA", name: "Fly One" },
  { iata: "6W", icao: "SOV", name: "Saratov Airlines" },
  { iata: "U6", icao: "SVR", name: "Ural Airlines" },
  { iata: "S7", icao: "SBI", name: "S7 Airlines" },
  { iata: "UT", icao: "UTA", name: "UTair" },
  { iata: "N4", icao: "NWS", name: "Nordwind Airlines" },
  { iata: "5N", icao: "AUL", name: "Nordavia" },
  { iata: "FV", icao: "SDM", name: "Rossiya Airlines" },
  { iata: "7R", icao: "BRB", name: "Rusline" },
  { iata: "DP", icao: "FCA", name: "Pobeda Airlines" },
  { iata: "WZ", icao: "RWZ", name: "Red Wings Airlines" },
  { iata: "GH", icao: "GHA", name: "Globus Airlines" },
  { iata: "UN", icao: "TSO", name: "Transaero Airlines" },
  { iata: "HO", icao: "DKH", name: "Juneyao Airlines" },
  { iata: "GS", icao: "GCR", name: "Tianjin Airlines" },
  { iata: "BK", icao: "OKA", name: "Okay Airways" },
  { iata: "Y8", icao: "YZR", name: "Suparna Airlines" },
  { iata: "8L", icao: "LKE", name: "Lucky Air" },
  { iata: "UQ", icao: "UCR", name: "Urumqi Air" },
  { iata: "GT", icao: "GBL", name: "Air Guilin" },
  { iata: "NS", icao: "HBR", name: "Hebei Airlines" },
  { iata: "A4", icao: "SWD", name: "Southern World Airlines" },
  { iata: "DR", icao: "RPA", name: "Ruili Airlines" },
  { iata: "RY", icao: "RJC", name: "Jiangxi Air" },
  { iata: "JR", icao: "JOY", name: "Joy Air" },
  { iata: "CN", icao: "GDC", name: "Grand China Air" },
  { iata: "PN", icao: "CHB", name: "West Air China" },
  { iata: "WA", icao: "KLC", name: "KLM Cityhopper" },
  { iata: "CL", icao: "CLH", name: "Lufthansa CityLine" },
  { iata: "EN", icao: "DLA", name: "Air Dolomiti" },
  { iata: "4Y", icao: "DNM", name: "Eurowings Discover" },
  { iata: "IQ", icao: "QAZ", name: "Qazaq Air" },
  { iata: "FY", icao: "FFM", name: "Firefly" },
  { iata: "RI", icao: "MDL", name: "Mandala Airlines" },
  { iata: "SL", icao: "THA", name: "Thai Lion Air" },
  { iata: "DD", icao: "NOK", name: "Nok Air" },
  { iata: "XJ", icao: "TAX", name: "Thai AirAsia X" },
  { iata: "PQ", icao: "PBU", name: "Philippines AirAsia" },
  { iata: "OX", icao: "OAE", name: "Orient Thai Airlines" },
  { iata: "K7", icao: "AAP", name: "Air KBZ" },
  { iata: "LQ", icao: "LMU", name: "Lanmei Airlines" },
  { iata: "QD", icao: "ESS", name: "JC International Airlines" },
];

// Normalize search for accent-insensitive matching
function normalize(str: string): string {
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase();
}

export function searchAirlines(keyword: string, limit = 15): AirlineData[] {
  if (!keyword || keyword.length < 1) {
    // Return popular airlines when no search
    const popular = ["LA", "G3", "AD", "AA", "DL", "UA", "EK", "QR", "BA", "LH", "AF", "TK", "AV", "CM", "TP"];
    return ALL_AIRLINES.filter(a => popular.includes(a.iata)).slice(0, limit);
  }
  const kw = normalize(keyword);
  // Exact IATA match first
  const exact = ALL_AIRLINES.filter(a => a.iata === kw);
  const partial = ALL_AIRLINES.filter(a =>
    a.iata !== kw && (
      a.iata.includes(kw) ||
      a.icao.includes(kw) ||
      normalize(a.name).includes(kw)
    )
  );
  return [...exact, ...partial].slice(0, limit);
}
