ALTER TABLE public.ai_knowledge_base 
ADD COLUMN IF NOT EXISTS taxonomy JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT NULL,
ADD COLUMN IF NOT EXISTS confidence NUMERIC DEFAULT NULL;